spring:
  application:
    name: gallery-service
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/image
#    username: root
#    password: 123456
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: saimon
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    database-plataform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2 
      
server:
  port: 8200
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
